apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: <ip_address_pool_name>        # e.g., metallb-ip-pool
  namespace: <namespace>              # e.g., metallb-system
spec:
  addresses:
    - <ip_range>                      # e.g., 10.0.0.4-10.0.0.6
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: <l2_advertisement_name>       # e.g., metallb-l2-advertisement
  namespace: <namespace>              # e.g., metallb-system
